### Jupyter notebook on AP's video tutorial

This is the first time im choosing to use a jupyter notebook, but I think its going to go really well for this style of coding. I'm excited actually.

importing torch to use the PyTorch library

In [1]:
import torch

built some tensors, the main datastructure used in machine learning. The tensor datastructure has a few cool arguments
- first one is the matrix
- second one is the datatype of the elements
- third one specifies a device. This can be the GPU (cuda) or the CPU (default)
- fourth one specifies if this tensor requires an *autograd*, pytorch's backpropagation algorithm

by convention, you specify the device as 
```python
device = "cuda" if torch.cuda.is_available() else "cpu" 
```

as this automatically handles the decision as the resource is available on a user's machine.

tensor objects have a stylized print method too, which is cool

In [10]:
my_device = "cuda" if torch.cuda.is_available() else "cpu"

int_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
float_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
cuda_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=my_device)
backprop_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=my_device, requires_grad=True)

print(int_tensor)
print(float_tensor)
print("\n")
print("backprop tensor:  ", backprop_tensor)
print("backprop tensor device:  ",backprop_tensor.device)
print("backprop tensor shape:  ",backprop_tensor.shape)
print("backprop tensor datatype:  ",backprop_tensor.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


backprop tensor:   tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
backprop tensor device:   cpu
backprop tensor shape:   torch.Size([2, 3])
backprop tensor datatype:   torch.float32


Some other ways you can initialize a tensor
- ```torch.empty()``` uses garbage memory. dont use this unless you know what you're doing
- ```torch.zeros()``` initializes all elements of the tensor
- ``torch.rand()`` initializes elements with values picked from a normal distribution
- `torch.ones()` is pretty obvious, like zeroes
- ```torch.eye()``` creates an identity matrix. note its size arguments are not inside a tuple
- build a range of values with ```torch.arange()``` from start to end, by incrementing step value
- build another range with `torch.linspace()` from start to end, but steps determines the number of entries and evenly increments all elements

- `torch.diag(torch.some-tensor)` preserves values along the diagonal of the tensor argument, like multiplying with an identity matrix

- `torch.uniform()` uses a uniform dist instead of norm

you can also chain these initialization statements, like building the tensor with garbage memory and a fixed size, then calling .rand() on it. note that when calling the second function, convention has you place an underscore before the "()"

```python
x = torch.empty(size=(1,5)).normal_(mean=0, std=1)
```
note the underscore after normal

In [21]:
x = torch.empty(size = (3, 3))
y = torch.zeros((3, 3)) #size not needed to be specified
z = torch.rand((3, 3))
ones = torch.ones((3, 3))
i = torch.eye(5, 5)
 
sequence = torch.arange(start=0, end=5, step=1)
other_sequence = torch.linspace(start=0.1, end=1, steps=10)


''' 

print("empty array is composed of garbage memory:\n", x)
print("zeroes array is initialized zeroes:\n", y)
print("random array picks values from a norm dist:\n", z)
print("ones is pretty obvious:\n", ones)
print("i is the identity matrix. used in lin alg:\n", i)

'''


print('\nsequences\n')
print("sequence A:\n", sequence)
print("sequence B:\n", other_sequence)

print("diagonal:\n", torch.diag(torch.rand((3, 3))))
print("chaining:\n", torch.empty(size=(3,3)).uniform_(0,1))
print("more chaining:\n", torch.empty(size=(1,5)).normal_(mean=0, std=1))



sequences

sequence A:
 tensor([0, 1, 2, 3, 4])
sequence B:
 tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
diagonal:
 tensor([0.5629, 0.6385, 0.3835])
chaining:
 tensor([[0.8776, 0.0230, 0.3836],
        [0.7094, 0.8987, 0.8067],
        [0.7813, 0.7041, 0.2490]])
more chaining:
 tensor([[ 0.5210,  0.7509, -0.7612, -1.3762, -0.5968]])
